sudo: false
language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  global:
    - LIBBITCOIN_URL=http://bitwatch.co/uploads/lib/libbitcoinconsensus.so # hack!
    - LIBBITCOIN_HASH=27831e7eb06c13b2fb1a58ba1462272d1e97791eb282034a09e4ef95ae9b1954

cache:
  directories:
  - $HOME/.gradle/caches

install:
  - mkdir -p src/main/resources # hack!
  - wget $LIBBITCOIN_URL --output-document=src/main/resources/libbitcoinconsensus.so
  - echo "$LIBBITCOIN_HASH  src/main/resources/libbitcoinconsensus.so" | sha256sum -c

script:
  - ./gradlew clean test
